# Generated by Django 2.2.7 on 2019-11-15 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='videoid',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='userid',
            new_name='user',
        ),
    ]
