# Generated by Django 2.2.7 on 2019-11-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0003_result_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='target_result',
            field=models.TextField(),
        ),
    ]
