# Generated by Django 2.2.7 on 2019-11-23 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0004_auto_20191122_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='type',
            new_name='viewtype',
        ),
        migrations.AddField(
            model_name='view',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='identify.Channel'),
        ),
        migrations.AddField(
            model_name='view',
            name='videoonline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='identify.VideoOnline'),
        ),
    ]
