# Generated by Django 2.2.7 on 2019-11-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0005_auto_20191122_2235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='ViewCount',
        ),
    ]
