# Generated by Django 2.2.7 on 2019-11-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0005_auto_20191119_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_video', to='identify.Video'),
        ),
        migrations.AlterField(
            model_name='result',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_video', to='identify.Video'),
        ),
    ]
