# Generated by Django 2.2.7 on 2019-11-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0006_auto_20191122_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewcount',
            name='viewtype',
        ),
    ]
