# Generated by Django 2.2.7 on 2019-11-23 07:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0007_remove_viewcount_viewtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewcount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular ViewCount', primary_key=True, serialize=False),
        ),
    ]
