# Generated by Django 2.2.7 on 2019-11-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0009_auto_20191122_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewcount',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
